name: release
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/loom-cache
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build
        run: ./gradlew build

      - name: Upload GitHub release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/libs/*.jar;!build/libs/*-sources.jar;!build/libs/*-dev.jar'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
